### ISSUE TITLE
How do you handle authentication?

### ISSUE THREAD

**Issue by rhewitt22** [cedricdelpoux/gatsby-source-strava#1]
Hi!

I'm new to Gatsby and I'm experimenting with source plugins. I'm interested in how you handle authentication with APIs that use OAuth. This plugin makes it look easy, just paste in your Strava API access token, but doesn't that token change regularly? How do you automate the refresh token, or do you just manually go back into your account and paste in the new value each time?

## Edit

It looks like Strava [recently changed](https://developers.strava.com/docs/oauth-updates/) their approach to authentication for v3 of the API. Access tokens are only valid for six hours now. Instead [you have to use a refresh token](https://developers.strava.com/docs/authentication/#refresh-expired-access-tokens) when your access token has expired. The request requires your client id and client secret, too.

```
const getAccessToken = config => {
  return axios
    .post(`https://www.strava.com/oauth/token`, {
      grant_type: 'refresh_token',
      refresh_token: config.refresh_token,
      client_id: config.id,
      client_secret: config.secret,
    })
};
```

**Comment by patrick91** [comment]
@rhewitt22 did you find a way to handle this on CI?

**Comment by rhewitt22** [comment]
I ended up writing my own. You have to generate a refresh token manually. I used postman. This helped me: https://stackoverflow.com/questions/52880434/problem-with-access-token-in-strava-api-v3-get-all-athlete-activities

https://github.com/rhewitt22/website/blob/master/plugins/gatsby-source-strava/gatsby-node.js

Roy

**Comment by patrick91** [comment]
@rhewitt22 thank you, I'll check it out :)

**Comment by cedricdelpoux** [comment]
Please checkout the new `2.x.x-beta` version :)

**Comment by cedricdelpoux** [comment]
Please checkout the new `2.x.x-beta` version :)
